export enum ExpenseCategory {
  FOOD = "FOOD",
  TRANSPORTAION = "TRANSPORTAION",
  UTILITIES = "UTILITIES",
  ENTERTAINMENT = "ENTERTAINMENT",
  HEALTHCARE = "HEALTHCARE",
  EDUCATION = "EDUCATION",
  HOUSING = "HOUSING",
  PERSONAL = "PERSONAL",
  SAVINGS = "SAVINGS",
  OTHER = "OTHER",
}
